//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        public int ID { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
