//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines
    {
        public int ID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public string Dosage { get; set; }
        public string Usage { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
