//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public string TCNo { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
