//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierMaterials
    {
        public int ID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
