//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatments
    {
        public int ID { get; set; }
        public Nullable<int> DentistID { get; set; }
        public string PatientID { get; set; }
        public Nullable<int> TreatmentTypeID { get; set; }
        public Nullable<int> ToothNumber { get; set; }
        public string TreatmentDescription { get; set; }
        public Nullable<System.DateTime> TreatmentTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
